{
 "title": "BentoML",
 "time": { "from": "now-5m", "to": "now-4s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {
     "query": "bentoml_api_server_request_in_progress{endpoint=\"/predict\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"tecobsml-example\"}[5m])) without (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_working_set_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{pod=\"tecobsml-example\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api_server_request_duration_seconds (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bentoml_api_server_request_duration_seconds_bucket{endpoint=\"/predict\", service_name=\"$service_name\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "runner_request_duration_seconds (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bentoml_runner_request_duration_seconds_bucket{endpoint=\"/predict\", service_name=\"$service_name\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "api_server_request_total per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(bentoml_api_server_request_total{endpoint=\"/predict\", service_name=\"$service_name\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "runner_request_total per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(bentoml_runner_request_total{endpoint=\"/predict\", service_name=\"$service_name\"}[$__rate_interval])"
    }
   ]
  }
 ]
}