prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

# adapted from https://stackoverflow.com/a/62011141
extraScrapeConfigs: |
  - job_name: 'kubernetes-pod-scrape-every-2s'

    scrape_interval: 2s

    kubernetes_sd_configs:
      - role: pod

    relabel_configs:
      #Custom
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_every_2s]
        action: keep
        regex: true

      # Boilerplate
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node