tempo:
  reportingEnabled: false
  # Tempo server configuration
  # Refers to https://grafana.com/docs/tempo/latest/configuration/#server
  storage:
    trace:
      # tempo storage backend
      # refer https://github.com/grafana/tempo/tree/master/docs/tempo/website/configuration
      ## Use s3 for example
      backend: s3
      s3:
        bucket: tempo                                   # store traces in this bucket
        endpoint: minio:9000  # api endpoint
        # access_key: ...                                 # optional. access key when using static credentials.
        # secret_key: ...                                 # optional. secret key when using static credentials.
        insecure: true                                 # optional. enable if endpoint is http

  # -- Environment variables to add
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-user
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-password

tempoQuery:
  enabled: true
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-user
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-password
