apiVersion: v1
kind: ConfigMap
metadata:
  name: bentoml-tecobsml-example
  namespace: technical-observability-for-ml
data:
  bentoml_configuration.yaml: |
    tracing:
      exporter_type: otlp
      sample_rate: 1.0
      otlp:
        protocol: http
        endpoint: http://tempo:4318/v1/traces
      excluded_urls: readyz,livez,healthz,static_content,docs,metrics
    api_server:
      http:
        port: 3010
    monitoring:
      enabled: false
    runners:
      doc_classifier:
        batching:
          enabled: true