apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/scrape_every_2s: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3010"
  labels:
    run: tecobsml-example
  name: tecobsml-example
  namespace: technical-observability-for-ml
spec:
  containers:
  - image: notniknot/tecobsml:example
    name: tecobsml-example
    resources:
      limits:
        memory: "4Gi"
        cpu: "1000m"
    env:
    - name: BENTOML_CONFIG
      value: "/config/bentoml_configuration.yaml"
    volumeMounts:
    - name: bentoml-configuration
      mountPath: /config
  volumes:
    - name: bentoml-configuration
      configMap:
        name: bentoml-tecobsml-example